---
- name: Configure OPS445 Lab VM
  hosts: vmlab
  become: yes
  vars:
    seneca_id: lbudhathoki
    ssh_pub_key: "{{ lookup('file', '/home/lbudhathoki/.ssh/id_rsa.pub') }}"
    lab_dirs:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8

  tasks:

    - name: Update Apache
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user with sudo access
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Setup SSH directory for new user
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0700'

    - name: Copy SSH public key to new user
      copy:
        content: "{{ ssh_pub_key }}"
        dest: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0600'

    - name: Create lab directories using a loop
      file:
        path: "/home/{{ seneca_id }}/ops445/{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ lab_dirs }}"

